---
title: 統計モデリング
format: html
lang: ja
execute: 
  eval: false
ascii: false
keep-ipynb: true
jupyter:
  jupytext:
    formats: 'ipynb,qmd'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.14.5
  kernelspec:
    display_name: R
    language: R
    name: ir
---

## 線形モデル

### 単回帰モデル

```{r}
# 気温のデータを作成
temperature <- seq(18, 40, 4)
# アイスクリームの売り上げのデータを作成
icecream_sales <- c(28, 45, 72, 82, 96, 100)
```

```{r}
# 散布図の作成
plot(temperature, icecream_sales)
```

```{r}
#| eval: false
#| echo: true
# 単回帰モデルの構築
# lm()関数の引数に 目的変数 ~ 説明変数 の形式で指定する
model <- lm(formula = ___ + ___)
```

```{r}
#| eval: false
#| echo: true
# intercept... 切片
# coefficient... 傾き（係数）
coefficients(model)
```

```{r}
# 回帰直線の追加
abline(model)
```

```{r}
# 新たなデータに対する予測
predict(model, data.frame(temperature = 30))
```

```{r}
# p値を含む結果の出力
summary(model)
```

### 重回帰モデル

```{r}
# 重回帰モデルの構築
humidity <- c(0.65, 0.8, 0.75, 0.85, 0.9, 0.8)
wind_speed <- c(2, 3, 4, 6, 3, 1)
model <- lm(icecream_sales ~ temperature + humidity + wind_speed)

coefficients(model)

summary(model)
```

## 一般化線形モデル

```{r}
# 『データ解析のための統計モデリング入門』（久保2012）からデータを利用
# 植物の種子数と体サイズについての架空のデータ
d <- read.csv("https://kuboweb.github.io/-kubo/stat/iwanamibook/fig/poisson/data3a.csv")

head(d)
# y... 植物の種子数
# x... 体サイズ
# f... 施肥処理（c... 処理なし、t... 処理あり）
```

```{r}
model <- glm(formula = ___, data = ___)
summary(model)
```

```{r}
predict(model, newdata = data.frame(x = 12, f = "C"), type = "response")
predict(model, newdata = data.frame(x = 12, f = "T"), type = "response")
```



